FROM golang:latest

WORKDIR /app

COPY . .

COPY snowflakebenchmark /app/

RUN go mod download

RUN go build -o snowflakebenchmark main.go

# Start a shell to keep the container running, instead of executing the benchmark immediately
CMD [ "sh" ]
