version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    container_name: postgres-benchmark
    ports:
      - '5571:5432'
    environment:
      POSTGRES_USER: postgres-benchmark
      POSTGRES_PASSWORD: postgres-benchmark
      POSTGRES_DB: postgres-benchmark
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/scripts.sql
    networks:
      - custom_network

  uuid_benchmark:
    build:
      context: .
      dockerfile: Dockerfile.uuid
    container_name: uuid-benchmark
    depends_on:
      - db
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    command: tail -f /dev/null

  snowflake_benchmark:
    build:
      context: .
      dockerfile: Dockerfile.snowflake
    container_name: snowflake-benchmark
    depends_on:
      - db
    networks:
      - custom_network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    command: tail -f /dev/null

networks:
  custom_network:
    driver: bridge
