FROM golang:latest

WORKDIR /app

COPY . .

RUN go mod download

RUN go build -o uuidbenchmark uuidbenchmark.go

# Start a shell to keep the container running, instead of executing the benchmark immediately
CMD [ "sh" ]
