FROM golang:latest

WORKDIR /app

COPY . .

RUN go mod download

RUN go build -o uuidbenchmark.out ./uuidbenchmark/main.go

RUN chmod +x uuidbenchmark.out

# Create a non-root user and switch to it
RUN useradd -m myuser
USER myuser

# Start a shell to keep the container running, instead of executing the benchmark immediately
CMD [ "sh" ]
